name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Composer install
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run psalm
        if: always()
        run: ./vendor/bin/psalm --threads=2 --output-format=github

      - name: Run php-cs-fixer
        if: always()
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run Unit tests
        if: always()
        run: ./vendor/bin/phpunit tests/
